const catalog=[
{name:"City",subs:["Trains","Police","Fire","Construction","Vehicles","Space","Airport","Harbor","Food","Jungle / Exploration"]},
{name:"Technic",subs:["Cars","Motorcycles","Construction","Racing","Space","Aircraft"]},
{name:"Icons",subs:["Vehicles","Landmarks","Botanical Collection","Modular Buildings","Entertainment","Seasonal"]},
{name:"Ideas",subs:["Space","Nature","Movies & TV","Games","Music","Objects & Display"]},
{name:"Creator 3in1",subs:["Animals","Vehicles","Buildings","Space"]},{name:"Speed Champions",subs:["Supercars","Racing","Formula 1"]},
{name:"Friends",subs:["Adventure","Animals","City Life","Food","Travel"]},{name:"NINJAGO",subs:["Dragons","Mechs","Vehicles","Temples"]},
{name:"Star Wars",subs:["Starships","Droids","Dioramas","Helmets","Battle"]},{name:"Minecraft",subs:["Biomes","Mobs","Buildings","Adventure"]},
{name:"Disney",subs:["Princess","Movies","Characters","Castles"]},{name:"Harry Potter",subs:["Hogwarts","Diagon Alley","Creatures","Vehicles"]},
{name:"Marvel",subs:["Avengers","Spider-Man","Guardians","Display"]},{name:"DC",subs:["Batman","Vehicles","Display"]},
{name:"DreamZzz",subs:["Dream Creatures","Vehicles","Locations"]},{name:"Animal Crossing",subs:["Characters","Homes","Island"]},
{name:"Sonic",subs:["Characters","Levels","Vehicles"]},{name:"Super Mario",subs:["Mario Kart","Characters","Courses","Display"]},
{name:"Art",subs:["Music","Nature","Characters","Landmarks"]},{name:"Architecture",subs:["Skylines","Landmarks"]},
{name:"Seasonal",subs:["Halloween","Christmas","Easter","Valentine"]}];
const KEY="ytMusicLibrary.v2",OLD="ytMusicLibrary.v1";
let data=load();
function load(){try{let x=localStorage.getItem(KEY)||localStorage.getItem(OLD);let d=x?JSON.parse(x):{};return {prompts:d.prompts||{},audio:d.audio||{}}}catch(e){return {prompts:{},audio:{}}}}
const slug=s=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const key=(t,s)=>slug(t)+"__"+slug(s), esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(s){let e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1400)}
function keysFor(t,s){return s?[key(t,s)]:catalog.find(x=>x.name===t).subs.map(x=>key(t,x))}
function stats(t,s){let ks=t?keysFor(t,s):Object.keys(data.prompts),ps=ks.flatMap(k=>data.prompts[k]||[]),aud=(t?ks:Object.keys(data.audio)).flatMap(k=>data.audio[k]||[]);return{p:ps.length,g:ps.filter(x=>x.generated).length,a:ps.filter(x=>x.approved).length,y:aud.length}}
function statline(x){return `${x.p} prompts · ${x.g} generated · ${x.a} approved · ${x.y} library`}
function summary(){let s=stats();document.getElementById("summary").innerHTML=`<div class="summary"><div class="metric"><strong>${s.p}</strong><span>AI prompts</span></div><div class="metric"><strong>${s.g}</strong><span>Generated tracks</span></div><div class="metric"><strong>${s.a}</strong><span>Approved tracks</span></div><div class="metric"><strong>${s.y}</strong><span>YouTube Library tracks</span></div></div>`}
function home(q=""){let qq=q.toLowerCase();let cards=catalog.filter(t=>!qq||t.name.toLowerCase().includes(qq)||t.subs.some(s=>s.toLowerCase().includes(qq))).map(t=>{let st=stats(t.name);let subs=t.subs.filter(s=>!qq||t.name.toLowerCase().includes(qq)||s.toLowerCase().includes(qq));return `<div class="card"><div class="theme-head"><div><h2><a class="theme-link" href="#theme/${slug(t.name)}">${t.name}</a></h2><div class="progress"><i style="width:${st.p?Math.round(st.a/st.p*100):0}%"></i></div></div><span class="stats">${statline(st)}</span></div><div class="subtree">${subs.map(s=>`<div class="subrow"><a class="theme-link" href="#theme/${slug(t.name)}/${slug(s)}">${s}</a><span class="stats">${statline(stats(t.name,s))}</span></div>`).join("")}</div></div>`}).join("");return `<div class="crumb">LEGO</div><div class="searchrow"><input class="search" id="search" value="${esc(q)}" placeholder="Search theme or subtheme…"></div>`+(cards||'<div class="empty">Nothing found.</div>')}
function themePage(t){return `<div class="crumb"><a href="#">LEGO</a> / ${t.name}</div><div class="section-head"><h1>${t.name}</h1><span class="stats">${statline(stats(t.name))}</span></div><div class="navchips">${t.subs.map(s=>`<a class="chip" href="#theme/${slug(t.name)}/${slug(s)}">${s}</a>`).join("")}</div>`+t.subs.map(s=>section(t.name,s)).join("")}
function section(t,s){let k=key(t,s),ps=data.prompts[k]||[],aud=data.audio[k]||[],st=stats(t,s);return `<section class="card section" id="${slug(s)}"><div class="section-head"><h2>${s}</h2><span class="pill">${statline(st)}</span></div><h3>AI music prompts</h3>${ps.length?ps.map((p,i)=>`<div class="prompt"><div class="num">${i+1}.</div><div class="prompt-text">${esc(p.text)}</div><button onclick="copyPrompt('${k}',${i})">Copy</button><label class="status"><input type="checkbox" ${p.generated?"checked":""} onchange="toggle('${k}',${i},'generated',this.checked)">Generated</label><label class="status"><input type="checkbox" ${p.approved?"checked":""} onchange="toggle('${k}',${i},'approved',this.checked)">Approved</label><button class="danger delete" onclick="delPrompt('${k}',${i})">×</button></div>`).join(""):'<div class="empty">No prompts yet.</div>'}<div class="addbar"><textarea id="new-${k}" rows="2" placeholder="Paste one prompt, or several prompts separated by blank lines…"></textarea><button class="primary" onclick="addPrompt('${k}')">Add prompt(s)</button></div><h3>YouTube Audio Library</h3>${aud.length?`<table class="audio-table"><tr><th>Track</th><th>Artist / note</th><th></th></tr>${aud.map((a,i)=>`<tr><td>${esc(a.title)}</td><td>${esc(a.note)}</td><td><button class="danger" onclick="delAudio('${k}',${i})">×</button></td></tr>`).join("")}</table>`:'<div class="empty">No downloaded tracks recorded yet.</div>'}<div class="addbar"><input id="at-${k}" placeholder="Track name"><input id="an-${k}" placeholder="Artist / note"><button onclick="addAudio('${k}')">Add track</button></div></section>`}
function render(){summary();let parts=location.hash.slice(1).split("/");if(parts[0]==="theme"){let t=catalog.find(x=>slug(x.name)===parts[1]);app.innerHTML=t?themePage(t):home();if(parts[2])setTimeout(()=>document.getElementById(parts[2])?.scrollIntoView(),0)}else app.innerHTML=home();let se=document.getElementById("search");if(se)se.oninput=e=>app.innerHTML=home(e.target.value)}
window.copyPrompt=(k,i)=>navigator.clipboard.writeText(data.prompts[k][i].text).then(()=>toast("Prompt copied"));
window.toggle=(k,i,f,v)=>{data.prompts[k][i][f]=v;if(f==="approved"&&v)data.prompts[k][i].generated=true;save();render()};
window.addPrompt=k=>{let e=document.getElementById("new-"+k),items=e.value.trim().split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);if(!items.length)return;(data.prompts[k]??=[]).push(...items.map(text=>({text,generated:false,approved:false})));save();render();toast(items.length+" prompt(s) added")};
window.delPrompt=(k,i)=>{if(confirm("Delete this prompt?")){data.prompts[k].splice(i,1);save();render()}};
window.addAudio=k=>{let t=document.getElementById("at-"+k),n=document.getElementById("an-"+k);if(!t.value.trim())return;(data.audio[k]??=[]).push({title:t.value.trim(),note:n.value.trim()});save();render();toast("Track added")};
window.delAudio=(k,i)=>{data.audio[k].splice(i,1);save();render()};
function download(){let payload={app:"YouTube Music Library",version:2,exportedAt:new Date().toISOString(),data};let b=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="youtube-music-library-backup.json";a.click();URL.revokeObjectURL(a.href)}
exportBtn.onclick=download;importBtn.onclick=()=>importFile.click();importFile.onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text()),d=j.data||j;if(!d.prompts||!d.audio)throw 0;if(confirm("Import will replace current browser data. Continue?")){data={prompts:d.prompts,audio:d.audio};save();render();toast("Backup imported")}}catch(x){alert("Invalid backup file.")}e.target.value=""};
addEventListener("hashchange",render);render();